"""Synchronous Python SDK for ASAREE."""

from __future__ import annotations

from asaree_client._transport import RetryPolicy
from asaree_client.client import AsareeClient
from asaree_client.exceptions import (
    AsareeAPIError,
    AsareeAuthenticationError,
    AsareeBadRequestError,
    AsareeConflictError,
    AsareeConnectionError,
    AsareeError,
    AsareeNotFoundError,
    AsareeServerError,
    AsareeTimeoutError,
    AsareeUnprocessableEntityError,
    AsareeUpstreamError,
)
from asaree_client.models import (
    Agent,
    ApiToken,
    ApiTokenPage,
    ApiTokenSummary,
    AuthTokens,
    BootstrapApiToken,
    BootstrapUser,
    CellRunBatch,
    DesignImpact,
    DesignRevision,
    DirectoryListing,
    DiscoveredSkill,
    Experiment,
    ExperimentArtifact,
    ExperimentResults,
    ExperimentRunResults,
    LLMConnectionCheck,
    LLMModelInfo,
    LLMModels,
    LLMSetting,
    MCPServer,
    MeasurementCapabilities,
    MeasurementPlanValidation,
    MeasurementPlanValidationIssue,
    Message,
    OKFBundle,
    OKFDocument,
    PromptPreview,
    Protocol,
    ProtocolRevision,
    ProtocolRun,
    RegisteredDataset,
    Replicate,
    Run,
    RunStep,
    Skill,
    SkillPage,
    SkillUrlPreview,
    TestRun,
    ToolCallResult,
    Trial,
    UserAccount,
    WorkspaceEvent,
)

try:
    # Written by hatch-vcs at build time from the repo's git tag.
    from asaree_client._version import __version__
except ImportError:
    # Imported from a source tree that was never built. _transport sends this as
    # the User-Agent, so it has to resolve to something -- say "unknown" rather
    # than a number that would go stale the way the old hardcoded one did.
    __version__ = "0.0.0+unknown"

__all__ = [
    "__version__",
    "Agent",
    "ApiToken",
    "ApiTokenPage",
    "ApiTokenSummary",
    "AsareeAPIError",
    "AsareeAuthenticationError",
    "AsareeBadRequestError",
    "AsareeClient",
    "AsareeConflictError",
    "AsareeConnectionError",
    "AsareeError",
    "AsareeNotFoundError",
    "AsareeServerError",
    "AsareeTimeoutError",
    "AsareeUnprocessableEntityError",
    "AsareeUpstreamError",
    "AuthTokens",
    "BootstrapApiToken",
    "BootstrapUser",
    "CellRunBatch",
    "DesignImpact",
    "DesignRevision",
    "DirectoryListing",
    "DiscoveredSkill",
    "Experiment",
    "ExperimentArtifact",
    "ExperimentResults",
    "ExperimentRunResults",
    "LLMConnectionCheck",
    "LLMModelInfo",
    "LLMModels",
    "LLMSetting",
    "MCPServer",
    "Message",
    "MeasurementCapabilities",
    "MeasurementPlanValidation",
    "MeasurementPlanValidationIssue",
    "OKFBundle",
    "OKFDocument",
    "PromptPreview",
    "Protocol",
    "ProtocolRevision",
    "ProtocolRun",
    "Replicate",
    "RegisteredDataset",
    "RetryPolicy",
    "Run",
    "RunStep",
    "Skill",
    "SkillPage",
    "SkillUrlPreview",
    "TestRun",
    "ToolCallResult",
    "Trial",
    "UserAccount",
    "WorkspaceEvent",
]
