"""Experiment-owned metric declarations."""

from __future__ import annotations

import uuid
from copy import deepcopy
from math import isfinite
from typing import Any

from asaree.services.measurement_engine import ensure_at_most_one_primary, parse_measurement_plan

MetricCatalogEntry = dict[str, str | bool]

CURRENT_RECOMMENDATION_SET_VERSION = 1

METRIC_CATALOG: tuple[MetricCatalogEntry, ...] = (
    {
        "key": "cost_usd",
        "name": "Cost",
        "shortDescription": "Estimated provider cost for the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "USD",
    },
    {
        "key": "duration_seconds",
        "name": "Duration",
        "shortDescription": "Wall-clock duration of the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "seconds",
    },
    {
        "key": "input_tokens",
        "name": "Input tokens",
        "shortDescription": "Tokens sent to the model during the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "tokens",
    },
    {
        "key": "output_tokens",
        "name": "Output tokens",
        "shortDescription": "Tokens generated by the model during the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "tokens",
    },
    {
        "key": "total_tokens",
        "name": "Total tokens",
        "shortDescription": "Combined input and output tokens for the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "tokens",
    },
    {
        "key": "tool_calls",
        "name": "Tool calls",
        "shortDescription": "Recorded tool-call attempts across attributed Agent runs.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "calls",
    },
    {
        "key": "tool_error_rate",
        "name": "Tool error rate",
        "shortDescription": "Failed tool calls divided by all tool-call attempts.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "mean",
        "unit": "rate",
    },
    {
        "key": "agent_loop_iterations",
        "name": "Agent-loop iterations",
        "shortDescription": "Distinct Agent reasoning-loop iterations in the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "iterations",
    },
    {
        "key": "critic_rejections",
        "name": "Critic rejections",
        "shortDescription": "Rejected critic-gate reviews during the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "reviews",
    },
    {
        "key": "critic_approvals",
        "name": "Critic approvals",
        "shortDescription": "Critic gates ending in an actual approval.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "neutral",
        "aggregation": "sum",
        "unit": "reviews",
    },
)
_CATALOG_BY_KEY = {str(entry["key"]): entry for entry in METRIC_CATALOG}
# Only metrics every run can produce. Tool calls is deliberately absent: an
# experiment is created before its canvas exists, and on a canvas with no tool
# wired it can never measure anything -- the metrics editor offers it once one is.
RECOMMENDED_RUNTIME_METRIC_KEYS = ("cost_usd", "duration_seconds", "total_tokens")
_RECOMMENDED_RUNTIME_METRIC_IDS = {
    "cost_usd": "runtime-cost",
    "duration_seconds": "runtime-duration",
    "total_tokens": "runtime-total-tokens",
}
_KINDS = {"runtime", "custom"}
_VALUE_TYPES = {"number", "boolean", "opaque"}
_DIRECTIONS = {"maximize", "minimize", "neutral"}
_AGGREGATIONS = {"mean", "sum", "none"}


def recommended_runtime_measurements() -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """Return the matching design declarations and executable baseline plan."""
    declarations: list[dict[str, Any]] = []
    definitions: list[dict[str, Any]] = []
    outputs: dict[str, str] = {}
    for key in RECOMMENDED_RUNTIME_METRIC_KEYS:
        catalog = _CATALOG_BY_KEY[key]
        metric_id = _RECOMMENDED_RUNTIME_METRIC_IDS[key]
        declaration = {
            "id": metric_id,
            "catalogKey": key,
            "name": catalog["name"],
            "description": catalog["shortDescription"],
            "kind": "runtime",
            "valueType": catalog["valueType"],
            "direction": catalog["defaultDirection"],
            "aggregation": catalog["aggregation"],
            "primary": False,
            "unit": catalog["unit"],
        }
        declarations.append(declaration)
        definitions.append(
            {
                "id": metric_id,
                "name": catalog["name"],
                "value_type": catalog["valueType"],
                "direction": catalog["defaultDirection"],
                "aggregation": catalog["aggregation"],
                "primary": False,
                "description": catalog["shortDescription"],
                "unit": catalog["unit"],
            }
        )
        outputs[key] = metric_id
    return declarations, {
        "metrics": definitions,
        "producers": [
            {
                "id": "runtime",
                "producer_id": "asaree.runtime",
                "kind": "runtime",
                "outputs": outputs,
                "artifacts": [],
                "config": {},
            }
        ],
        "inputs": [
            {
                "producer_binding_id": "runtime",
                "input_key": "facts",
                "source_key": "attempt.runtime",
            }
        ],
    }


def design_metrics_from_measurement_plan(document: Any) -> list[dict[str, Any]]:
    """Build the design declarations required by a caller-supplied plan."""
    plan = parse_measurement_plan(document)
    runtime_outputs = {
        metric_id: output_key
        for binding in plan.producers
        if binding.producer_id == "asaree.runtime"
        for output_key, metric_id in binding.outputs.items()
    }
    declarations: list[dict[str, Any]] = []
    for metric in plan.metrics:
        catalog_key = runtime_outputs.get(metric.id)
        declaration: dict[str, Any] = {
            "id": metric.id,
            "name": metric.name,
            "kind": "runtime" if catalog_key is not None else "custom",
            "valueType": metric.value_type,
            "direction": metric.direction,
            "aggregation": metric.aggregation,
            "primary": metric.primary,
        }
        if catalog_key is not None:
            declaration["catalogKey"] = catalog_key
        if metric.description is not None:
            declaration["description"] = metric.description
        if metric.unit is not None:
            declaration["unit"] = metric.unit
        declarations.append(declaration)
    return normalize_metrics(declarations, validate_custom_names=True)


def applied_metric_recommendations() -> dict[str, Any]:
    """Recommendation lifecycle for an experiment created with today's baseline."""
    return {
        "applied_version": CURRENT_RECOMMENDATION_SET_VERSION,
        "dismissed_version": None,
        "intentionally_removed_keys": [],
    }


def normalize_metrics(metrics: Any, *, validate_custom_names: bool = False) -> list[dict[str, Any]]:
    """Normalize legacy declarations while retaining unknown forward fields.

    This is intentionally a narrow JSONB-boundary migration rather than a DB
    migration: historical design specs remain readable and acquire stable IDs
    the next time they are saved without throwing away fields a newer client
    may have written.
    """
    if not isinstance(metrics, list):
        return []
    normalized: list[dict[str, Any]] = []
    for raw in metrics:
        if not isinstance(raw, dict):
            continue
        metric = deepcopy(raw)
        name = metric.get("name")
        if not isinstance(name, str) or not name.strip():
            continue
        name = name.strip()
        catalog_key = metric.get("catalogKey")
        catalog = _CATALOG_BY_KEY.get(catalog_key) if isinstance(catalog_key, str) else None
        if isinstance(metric.get("id"), str) and metric["id"]:
            metric["id"] = metric["id"]
        else:
            legacy_key = ":".join(
                str(value)
                for value in (
                    metric.get("catalogKey") or "",
                    name.casefold(),
                    metric.get("kind") or "custom",
                    metric.get("valueType") or "number",
                    metric.get("direction") or "maximize",
                )
            )
            metric["id"] = f"legacy-metric-{uuid.uuid5(uuid.NAMESPACE_URL, legacy_key)}"
        metric["name"] = name
        if catalog:
            metric["catalogKey"] = catalog["key"]
        description = metric.get("description")
        metric["description"] = (
            description.strip()
            if isinstance(description, str) and description.strip()
            else str(catalog["shortDescription"])
            if catalog
            else f"Legacy metric declaration for {name}."
        )
        metric["kind"] = (
            metric.get("kind") if metric.get("kind") in _KINDS else catalog["kind"] if catalog else "custom"
        )
        metric["valueType"] = (
            metric.get("valueType")
            if metric.get("valueType") in _VALUE_TYPES
            else catalog["valueType"]
            if catalog
            else "number"
        )
        metric["direction"] = (
            metric.get("direction")
            if metric.get("direction") in _DIRECTIONS
            else catalog["defaultDirection"]
            if catalog
            else "maximize"
        )
        metric["primary"] = bool(metric.get("primary"))
        metric["aggregation"] = (
            "mean"
            if metric["valueType"] == "boolean"
            else metric.get("aggregation")
            if metric.get("aggregation") in _AGGREGATIONS
            else catalog.get("aggregation", "mean")
            if catalog
            else "mean"
        )
        if metric["kind"] == "custom":
            metric["valueType"] = "opaque"
            metric["direction"] = "neutral"
            metric["aggregation"] = "none"
            metric["primary"] = False
        if metric.get("unit") is None and catalog and catalog.get("unit"):
            metric["unit"] = catalog["unit"]
        metric.pop("scoring", None)
        # Duplicate labels are a readiness problem, not a persistence error.
        # Custom-metric drafts autosave immediately (and several initially use
        # "Untitled custom metric"), so the measurement-plan validator blocks
        # production while still preserving every draft for repair.
        normalized.append(metric)
    ensure_at_most_one_primary(tuple(bool(metric["primary"]) for metric in normalized))
    return normalized


def normalize_design_spec(
    design_spec: dict[str, Any] | None, *, validate_metrics: bool = False
) -> dict[str, Any] | None:
    if design_spec is None:
        return None
    result = deepcopy(design_spec)
    factors = result.get("factors")
    if isinstance(factors, list):
        for factor in factors:
            if not isinstance(factor, dict) or not isinstance(factor.get("name"), str):
                continue
            if factor.get("level_type") == "llm_config":
                factor["level_type"] = "model_config"
            levels = factor.get("levels")
            if not isinstance(levels, list):
                continue
            defaults = [f"level{index}" for index in range(1, len(levels) + 1)]
            supplied = factor.get("level_labels")
            if isinstance(supplied, list) and len(supplied) == len(levels):
                factor["level_labels"] = [
                    label.strip() if isinstance(label, str) and label.strip() else defaults[index]
                    for index, label in enumerate(supplied)
                ]
            else:
                # Legacy factors have only their raw treatment values. Give
                # them short, stable labels on read/save without exposing a
                # long prompt or structured configuration in a CSV header.
                factor["level_labels"] = defaults
    if "metrics" in result:
        result["metrics"] = normalize_metrics(result["metrics"], validate_custom_names=validate_metrics)
    return result


def declared_primary_metric(metrics: Any) -> dict[str, Any] | None:
    """Return the one explicitly primary design metric, if one is declared."""
    return next((metric for metric in normalize_metrics(metrics) if metric["primary"]), None)


def validate_metric_values(metrics: Any, values: dict[str, Any] | None) -> dict[str, Any]:
    """Validate declared outcome values at the API boundary.

    Metric declarations are dynamic JSONB, so this is intentionally a
    declaration-driven validation rather than a database-column constraint.
    Unknown keys stay allowed for backwards-compatible externally reported
    metrics; declared custom metrics must honor their selected value type.
    """
    declared = {metric["name"]: metric for metric in normalize_metrics(metrics) if metric["kind"] != "runtime"}
    normalized: dict[str, Any] = {}
    for key, value in (values or {}).items():
        metric = declared.get(key)
        if metric is None:
            normalized[key] = value
            continue
        value_type = metric["valueType"]
        if value_type == "boolean":
            if not isinstance(value, bool):
                raise ValueError(f"Metric {key!r} must be Boolean.")
        elif value_type == "number":
            if isinstance(value, bool) or not isinstance(value, int | float) or not isfinite(float(value)):
                raise ValueError(f"Metric {key!r} must be a finite number.")
        elif value_type == "string" and not isinstance(value, str):
            raise ValueError(f"Metric {key!r} must be text.")
        normalized[key] = value
    return normalized
