"""Experiment-owned metric declarations and safe Agent evaluation context.

The catalog deliberately contains only execution telemetry the application
already records.  Scoring metrics promoted from controlled tools remain
possible as custom declarations; this module never makes a subject Agent a
metric evaluator.
"""

from __future__ import annotations

import re
import uuid
from copy import deepcopy
from math import isfinite
from typing import Any

MetricCatalogEntry = dict[str, str | bool]

METRIC_CATALOG: tuple[MetricCatalogEntry, ...] = (
    {
        "key": "cost_usd",
        "name": "Cost",
        "shortDescription": "Estimated provider cost for the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "USD",
        "contextEligible": True,
    },
    {
        "key": "duration_seconds",
        "name": "Duration",
        "shortDescription": "Wall-clock duration of the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "seconds",
        "contextEligible": True,
    },
    {
        "key": "input_tokens",
        "name": "Input tokens",
        "shortDescription": "Tokens sent to the model during the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "tokens",
        "contextEligible": True,
    },
    {
        "key": "output_tokens",
        "name": "Output tokens",
        "shortDescription": "Tokens generated by the model during the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "tokens",
        "contextEligible": True,
    },
    {
        "key": "total_tokens",
        "name": "Total tokens",
        "shortDescription": "Combined input and output tokens for the run.",
        "kind": "runtime",
        "valueType": "number",
        "defaultDirection": "minimize",
        "aggregation": "sum",
        "unit": "tokens",
        "contextEligible": True,
    },
)
_CATALOG_BY_KEY = {str(entry["key"]): entry for entry in METRIC_CATALOG}
_KINDS = {"runtime", "deterministic_evaluator", "model_judge", "agent_reported", "custom"}
_VALUE_TYPES = {"number", "boolean", "string"}
_DIRECTIONS = {"maximize", "minimize"}
_AGGREGATIONS = {"mean", "sum"}
_JUDGE_PROVIDERS = {"anthropic", "openai", "azure_foundry", "openrouter", "local"}
_DELIMITER = re.compile(r"</?experiment_evaluation_context>", re.IGNORECASE)


def model_judge_metrics(metrics: Any) -> list[dict[str, Any]]:
    """Configured numeric metrics safe for the controlled post-run judge."""
    return [
        metric
        for metric in normalize_metrics(metrics)
        if metric.get("kind") == "model_judge"
        and metric.get("valueType") == "number"
        and isinstance(metric.get("scoring"), dict)
        and metric["scoring"].get("method") == "model_judge"
        and isinstance(metric["scoring"].get("rubric"), str)
        and metric["scoring"]["rubric"].strip()
    ]


def normalize_metrics(metrics: Any, *, validate_custom_names: bool = False) -> list[dict[str, Any]]:
    """Normalize legacy declarations while retaining unknown forward fields.

    This is intentionally a narrow JSONB-boundary migration rather than a DB
    migration: historical design specs remain readable and acquire stable IDs
    the next time they are saved without throwing away fields a newer client
    may have written.
    """
    if not isinstance(metrics, list):
        return []
    normalized: list[dict[str, Any]] = []
    custom_names: set[str] = set()
    for index, raw in enumerate(metrics):
        if not isinstance(raw, dict):
            continue
        metric = deepcopy(raw)
        name = metric.get("name")
        if not isinstance(name, str) or not name.strip():
            continue
        name = name.strip()
        catalog_key = metric.get("catalogKey")
        catalog = _CATALOG_BY_KEY.get(catalog_key) if isinstance(catalog_key, str) else None
        if isinstance(metric.get("id"), str) and metric["id"]:
            metric["id"] = metric["id"]
        else:
            legacy_key = f"{name}:{metric.get('direction')}:{index}"
            metric["id"] = f"legacy-metric-{uuid.uuid5(uuid.NAMESPACE_URL, legacy_key)}"
        metric["name"] = name
        if catalog:
            metric["catalogKey"] = catalog["key"]
        description = metric.get("description")
        metric["description"] = (
            description.strip()
            if isinstance(description, str) and description.strip()
            else str(catalog["shortDescription"])
            if catalog
            else f"Legacy metric declaration for {name}."
        )
        metric["kind"] = (
            metric.get("kind") if metric.get("kind") in _KINDS else catalog["kind"] if catalog else "custom"
        )
        metric["valueType"] = (
            metric.get("valueType")
            if metric.get("valueType") in _VALUE_TYPES
            else catalog["valueType"]
            if catalog
            else "number"
        )
        metric["direction"] = (
            metric.get("direction")
            if metric.get("direction") in _DIRECTIONS
            else catalog["defaultDirection"]
            if catalog
            else "maximize"
        )
        metric["primary"] = bool(metric.get("primary"))
        metric["aggregation"] = (
            "mean"
            if metric["valueType"] == "boolean"
            else metric.get("aggregation")
            if metric.get("aggregation") in _AGGREGATIONS
            else catalog.get("aggregation", "mean")
            if catalog
            else "mean"
        )
        if metric.get("unit") is None and catalog and catalog.get("unit"):
            metric["unit"] = catalog["unit"]
        scoring = metric.get("scoring")
        if isinstance(scoring, dict) and scoring.get("method") == "model_judge":
            rubric = scoring.get("rubric")
            if not isinstance(rubric, str) or not rubric.strip():
                if validate_custom_names:
                    raise ValueError(f"Model-judge metric {name} needs a scoring rubric")
                metric.pop("scoring", None)
            else:
                normalized_scoring: dict[str, Any] = {"method": "model_judge", "rubric": rubric.strip()}
                reference = scoring.get("reference")
                if isinstance(reference, str) and reference.strip():
                    normalized_scoring["reference"] = reference.strip()
                minimum, maximum = scoring.get("min"), scoring.get("max")
                if minimum is not None and (isinstance(minimum, bool) or not isinstance(minimum, int | float)):
                    raise ValueError(f"Model-judge metric {name} has an invalid minimum")
                if maximum is not None and (isinstance(maximum, bool) or not isinstance(maximum, int | float)):
                    raise ValueError(f"Model-judge metric {name} has an invalid maximum")
                if minimum is not None:
                    normalized_scoring["min"] = float(minimum)
                if maximum is not None:
                    normalized_scoring["max"] = float(maximum)
                if minimum is not None and maximum is not None and minimum > maximum:
                    raise ValueError(f"Model-judge metric {name} must have a minimum no greater than its maximum")
                judge = scoring.get("judge")
                if judge is not None:
                    provider = judge.get("provider") if isinstance(judge, dict) else None
                    model = judge.get("model") if isinstance(judge, dict) else None
                    if provider not in _JUDGE_PROVIDERS or not isinstance(model, str) or not model.strip():
                        if validate_custom_names:
                            raise ValueError(f"Model-judge metric {name} needs a valid judge provider and model")
                    else:
                        normalized_scoring["judge"] = {"provider": provider, "model": model.strip()}
                metric["scoring"] = normalized_scoring
                metric["kind"] = "model_judge"
                metric["valueType"] = "number"
        elif metric.get("kind") == "model_judge" and validate_custom_names:
            raise ValueError(f"Model-judge metric {name} needs a scoring configuration")
        if validate_custom_names and metric["kind"] in {"custom", "model_judge"}:
            folded = name.casefold()
            if folded in custom_names:
                raise ValueError(f"Duplicate custom metric name: {name}")
            custom_names.add(folded)
        normalized.append(metric)
    if normalized:
        primary_index = next((index for index, metric in enumerate(normalized) if metric["primary"]), 0)
        for index, metric in enumerate(normalized):
            metric["primary"] = index == primary_index
    return normalized


def normalize_design_spec(
    design_spec: dict[str, Any] | None, *, validate_metrics: bool = False
) -> dict[str, Any] | None:
    if design_spec is None:
        return None
    result = deepcopy(design_spec)
    if "metrics" in result:
        result["metrics"] = normalize_metrics(result["metrics"], validate_custom_names=validate_metrics)
    return result


def validate_metric_values(metrics: Any, values: dict[str, Any] | None) -> dict[str, Any]:
    """Validate declared outcome values at the API boundary.

    Metric declarations are dynamic JSONB, so this is intentionally a
    declaration-driven validation rather than a database-column constraint.
    Unknown keys stay allowed for backwards-compatible externally reported
    metrics; declared custom metrics must honor their selected value type.
    """
    declared = {
        metric["name"]: metric
        for metric in normalize_metrics(metrics)
        if metric["kind"] != "runtime"
    }
    normalized: dict[str, Any] = {}
    for key, value in (values or {}).items():
        metric = declared.get(key)
        if metric is None:
            normalized[key] = value
            continue
        value_type = metric["valueType"]
        if value_type == "boolean":
            if not isinstance(value, bool):
                raise ValueError(f"Metric {key!r} must be Boolean.")
        elif value_type == "number":
            if isinstance(value, bool) or not isinstance(value, int | float) or not isfinite(float(value)):
                raise ValueError(f"Metric {key!r} must be a finite number.")
        elif value_type == "string" and not isinstance(value, str):
            raise ValueError(f"Metric {key!r} must be text.")
        normalized[key] = value
    return normalized


def _safe_context_text(value: Any) -> str:
    text = _DELIMITER.sub("[evaluation context delimiter]", str(value))
    return " ".join(text.splitlines()).strip()


def build_evaluation_context(metrics: Any, context_metric_ids: Any) -> str:
    """Build the one generated system-context block, with no result values."""
    selected = (
        {item for item in context_metric_ids if isinstance(item, str)}
        if isinstance(context_metric_ids, list)
        else set()
    )
    included = [metric for metric in normalize_metrics(metrics) if metric["id"] in selected]
    if not included:
        return ""
    lines = [
        "<experiment_evaluation_context>",
        "The following criteria describe how this experiment will assess the run.",
        "Use them as guidance, but do not invent or report metric results unless the task explicitly asks for an "
        "agent-reported value.",
        "",
    ]
    for metric in included:
        lines.append(f"- {_safe_context_text(metric['name'])} — {metric['direction']}")
        lines.append(f"  {_safe_context_text(metric['description'])}")
        if metric["kind"] == "runtime":
            lines.append("  Recorded by the runtime after execution; its final value is not available during this run.")
    lines.append("</experiment_evaluation_context>")
    return "\n".join(lines)


def compose_system_prompt(base_prompt: str, metrics: Any, context_metric_ids: Any) -> str:
    context = build_evaluation_context(metrics, context_metric_ids)
    return f"{base_prompt}\n\n{context}" if context else base_prompt
