"""user llm settings

Revision ID: e713d250f15b
Revises: 0699a4e14025
Create Date: 2026-08-04 23:18:49.434082
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = 'e713d250f15b'
down_revision: str | None = '0699a4e14025'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_llm_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_llm_settings_user_provider'),
    if_not_exists=True,
    )
    op.create_index(op.f('ix_user_llm_settings_user_id'), 'user_llm_settings', ['user_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_llm_settings_user_id'), table_name='user_llm_settings', if_exists=True)
    op.drop_table('user_llm_settings', if_exists=True)
    # ### end Alembic commands ###
