import type { DesignMetric } from '@/types/experiments'
import { newNodeId } from '@/lib/nodeId'

/**
 * The only client-side catalog of metric definitions.  A metric declaration
 * stores a snapshot of this metadata so an experiment remains intelligible if
 * the catalog changes later; the catalog is never a promise that an Agent can
 * calculate the metric itself.
 */
export type MetricKind = 'runtime' | 'custom'
export type MetricValueType = 'number' | 'boolean' | 'string' | 'opaque'
export type MetricDirection = 'maximize' | 'minimize' | 'neutral'
export type MetricAggregation = 'mean' | 'sum' | 'none'
export type MetricCategory = 'Efficiency' | 'Tokens' | 'Tools' | 'Agents' | 'Critics'
export type MetricSource = 'Run summary' | 'Protocol activity'

export interface MetricCatalogEntry {
  key: string
  name: string
  shortDescription: string
  kind: MetricKind
  valueType: MetricValueType
  defaultDirection: MetricDirection
  aggregation?: MetricAggregation
  unit?: string
  category: MetricCategory
  source: MetricSource
  recommended?: boolean
}

// This catalog owns display metadata only. The Design picker filters these
// entries through the measurement engine's discovered producer outputs.
export const METRIC_CATALOG: readonly MetricCatalogEntry[] = [
  { key: 'cost_usd', name: 'Cost', shortDescription: 'Estimated provider cost for the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'USD', category: 'Efficiency', source: 'Run summary', recommended: true },
  { key: 'duration_seconds', name: 'Duration', shortDescription: 'Wall-clock duration of the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'seconds', category: 'Efficiency', source: 'Run summary', recommended: true },
  { key: 'input_tokens', name: 'Input tokens', shortDescription: 'Tokens sent to the model during the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'tokens', category: 'Tokens', source: 'Run summary' },
  { key: 'output_tokens', name: 'Output tokens', shortDescription: 'Tokens generated by the model during the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'tokens', category: 'Tokens', source: 'Run summary' },
  { key: 'total_tokens', name: 'Total tokens', shortDescription: 'Combined input and output tokens for the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'tokens', category: 'Tokens', source: 'Run summary', recommended: true },
  { key: 'tool_calls', name: 'Tool calls', shortDescription: 'Recorded tool-call attempts across attributed Agent runs.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'calls', category: 'Tools', source: 'Protocol activity' },
  { key: 'tool_error_rate', name: 'Tool error rate', shortDescription: 'Failed tool calls divided by all tool-call attempts.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'mean', unit: 'rate', category: 'Tools', source: 'Protocol activity' },
  { key: 'agent_loop_iterations', name: 'Agent-loop iterations', shortDescription: 'Distinct Agent reasoning-loop iterations in the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'iterations', category: 'Agents', source: 'Protocol activity' },
  { key: 'critic_rejections', name: 'Critic rejections', shortDescription: 'Rejected critic-gate reviews during the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'reviews', category: 'Critics', source: 'Protocol activity' },
  { key: 'critic_approvals', name: 'Critic approvals', shortDescription: 'Critic gates ending in an actual approval.', kind: 'runtime', valueType: 'number', defaultDirection: 'neutral', aggregation: 'sum', unit: 'reviews', category: 'Critics', source: 'Protocol activity' },
  { key: 'critic_invocations', name: 'Critic invocations', shortDescription: 'Critic-gate reviews run during the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'neutral', aggregation: 'sum', unit: 'reviews', category: 'Critics', source: 'Protocol activity' },
  { key: 'critic_rejections_partial', name: 'Partial critic rejections', shortDescription: 'Rejections scoped to a targeted correction.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'reviews', category: 'Critics', source: 'Protocol activity' },
  { key: 'critic_rejections_full', name: 'Full critic rejections', shortDescription: 'Rejections asking the stage to reconsider its approach (includes unscoped ones).', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'reviews', category: 'Critics', source: 'Protocol activity' },
  { key: 'revision_rounds', name: 'Revision rounds', shortDescription: 'Worker reruns triggered by critic rejections.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'rounds', category: 'Critics', source: 'Protocol activity' },
  { key: 'prompt_sha256', name: 'Prompt SHA-256', shortDescription: 'Hash of the published stage prompts, critic criteria and output contracts.', kind: 'runtime', valueType: 'opaque', defaultDirection: 'neutral', aggregation: 'none', category: 'Agents', source: 'Protocol activity' },
  { key: 'capped_agent_runs', name: 'Capped agent runs', shortDescription: 'Reason+Act runs cut off by their iteration ceiling.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', aggregation: 'sum', unit: 'runs', category: 'Agents', source: 'Protocol activity' },
]

export const RECOMMENDED_METRIC_KEYS = METRIC_CATALOG.filter((entry) => entry.recommended).map((entry) => entry.key)

export function metricCatalogEntry(key: string | undefined): MetricCatalogEntry | undefined {
  return METRIC_CATALOG.find((entry) => entry.key === key)
}

function legacyId(metric: Partial<DesignMetric>): string {
  // Deterministic for old, read-only records; an edited/saved declaration is
  // normalized at the API boundary with the same stable value.
  const text = `${metric.catalogKey ?? ''}:${(metric.name ?? 'metric').toLocaleLowerCase()}:${metric.kind ?? 'custom'}:${metric.valueType ?? 'number'}:${metric.direction ?? 'maximize'}`
  let hash = 2166136261
  for (const char of text) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619)
  return `legacy-metric-${(hash >>> 0).toString(36)}`
}

/** Preserve unknown persisted fields while making pre-catalog metrics usable. */
export function normalizeDesignMetrics(metrics: DesignMetric[] | undefined): DesignMetric[] {
  const source = Array.isArray(metrics) ? metrics : []
  return source.flatMap((raw) => {
    if (!raw || typeof raw.name !== 'string' || !raw.name.trim()) return []
    const catalog = metricCatalogEntry(raw.catalogKey)
    if (raw.kind && !['runtime', 'custom'].includes(raw.kind)) return []
    const kind = raw.kind ?? catalog?.kind ?? 'custom'
    const id = typeof raw.id === 'string' && raw.id ? raw.id : legacyId(raw)
    const name = raw.name.trim()
    if (kind === 'custom') return [{ id, name, kind }]
    const metric: DesignMetric = {
      ...raw,
      id,
      catalogKey: catalog ? catalog.key : raw.catalogKey,
      name,
      description: typeof raw.description === 'string' && raw.description.trim()
        ? raw.description.trim()
        : catalog?.shortDescription ?? `Legacy metric declaration for ${raw.name.trim()}.`,
      kind,
      valueType: raw.valueType ?? catalog?.valueType ?? 'number',
      direction: raw.direction === 'maximize' || raw.direction === 'minimize' || raw.direction === 'neutral'
        ? raw.direction
        : (catalog?.defaultDirection ?? 'maximize'),
      aggregation: raw.valueType === 'boolean' ? 'mean' : (raw.aggregation === 'sum' ? 'sum' : raw.aggregation === 'none' ? 'none' : (catalog?.aggregation ?? 'mean')),
      primary: Boolean(raw.primary),
      unit: raw.unit ?? catalog?.unit,
      scoring: undefined,
    }
    return [metric]
  })
}

export function makeCatalogMetric(entry: MetricCatalogEntry, isPrimary: boolean): DesignMetric {
  return {
    id: newMetricId(),
    catalogKey: entry.key,
    name: entry.name,
    description: entry.shortDescription,
    kind: entry.kind,
    valueType: entry.valueType,
    direction: entry.defaultDirection,
    aggregation: entry.aggregation ?? 'mean',
    primary: isPrimary,
    unit: entry.unit,
  }
}

export function makeCustomMetric(input: { name: string }): DesignMetric {
  return {
    id: newMetricId(),
    name: input.name.trim(),
    kind: 'custom',
  }
}

// Metric IDs have the same browser requirement as canvas IDs: they must work
// in plain-HTTP development deployments as well as HTTPS, where
// crypto.randomUUID() is unavailable.
function newMetricId(): string {
  return newNodeId().replace(/^node-/, 'metric-')
}
