import type { DesignMetric, MetricScoringConfig } from '@/types/experiments'
import { newNodeId } from '@/lib/nodeId'

/**
 * The only client-side catalog of metric definitions.  A metric declaration
 * stores a snapshot of this metadata so an experiment remains intelligible if
 * the catalog changes later; the catalog is never a promise that an Agent can
 * calculate the metric itself.
 */
export type MetricKind = 'runtime' | 'deterministic_evaluator' | 'model_judge' | 'agent_reported' | 'custom'
export type MetricValueType = 'number' | 'boolean' | 'string'
export type MetricDirection = 'maximize' | 'minimize'

export interface MetricCatalogEntry {
  key: string
  name: string
  shortDescription: string
  kind: MetricKind
  valueType: MetricValueType
  defaultDirection: MetricDirection
  unit?: string
  contextEligible: boolean
}

// These are telemetry fields that the run-results service really records.
// There are intentionally no aspirational scoring metrics here: score
// promotion is a separate, controlled post-run operation.
export const METRIC_CATALOG: readonly MetricCatalogEntry[] = [
  { key: 'cost_usd', name: 'Cost', shortDescription: 'Estimated provider cost for the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', unit: 'USD', contextEligible: true },
  { key: 'duration_seconds', name: 'Duration', shortDescription: 'Wall-clock duration of the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', unit: 'seconds', contextEligible: true },
  { key: 'input_tokens', name: 'Input tokens', shortDescription: 'Tokens sent to the model during the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', unit: 'tokens', contextEligible: true },
  { key: 'output_tokens', name: 'Output tokens', shortDescription: 'Tokens generated by the model during the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', unit: 'tokens', contextEligible: true },
  { key: 'total_tokens', name: 'Total tokens', shortDescription: 'Combined input and output tokens for the run.', kind: 'runtime', valueType: 'number', defaultDirection: 'minimize', unit: 'tokens', contextEligible: true },
]

export function metricCatalogEntry(key: string | undefined): MetricCatalogEntry | undefined {
  return METRIC_CATALOG.find((entry) => entry.key === key)
}

function legacyId(metric: Partial<DesignMetric>, index: number): string {
  // Deterministic for old, read-only records; an edited/saved declaration is
  // normalized at the API boundary with the same stable value.
  const text = `${metric.name ?? 'metric'}:${metric.direction ?? 'maximize'}:${index}`
  let hash = 2166136261
  for (const char of text) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619)
  return `legacy-metric-${(hash >>> 0).toString(36)}`
}

/** Preserve unknown persisted fields while making pre-catalog metrics usable. */
export function normalizeDesignMetrics(metrics: DesignMetric[] | undefined): DesignMetric[] {
  const source = Array.isArray(metrics) ? metrics : []
  return source.flatMap((raw, index) => {
    if (!raw || typeof raw.name !== 'string' || !raw.name.trim()) return []
    const catalog = metricCatalogEntry(raw.catalogKey)
    const scoring = raw.scoring
    const normalizedScoring = scoring && typeof scoring === 'object' && !Array.isArray(scoring)
      && (scoring as MetricScoringConfig).method === 'model_judge'
      && typeof (scoring as MetricScoringConfig).rubric === 'string'
      && (scoring as MetricScoringConfig).rubric.trim()
      ? {
          method: 'model_judge' as const,
          rubric: (scoring as MetricScoringConfig).rubric.trim(),
          reference: typeof (scoring as MetricScoringConfig).reference === 'string'
            ? ((scoring as MetricScoringConfig).reference?.trim() || undefined)
            : undefined,
          min: typeof (scoring as MetricScoringConfig).min === 'number' ? (scoring as MetricScoringConfig).min : undefined,
          max: typeof (scoring as MetricScoringConfig).max === 'number' ? (scoring as MetricScoringConfig).max : undefined,
          judge: (scoring as MetricScoringConfig).judge
            && typeof (scoring as MetricScoringConfig).judge?.provider === 'string'
            && typeof (scoring as MetricScoringConfig).judge?.model === 'string'
            && (scoring as MetricScoringConfig).judge!.model.trim()
            ? {
                provider: (scoring as MetricScoringConfig).judge!.provider,
                model: (scoring as MetricScoringConfig).judge!.model.trim(),
              }
            : undefined,
        }
      : undefined
    return [{
      ...raw,
      id: typeof raw.id === 'string' && raw.id ? raw.id : legacyId(raw, index),
      catalogKey: catalog ? catalog.key : raw.catalogKey,
      name: raw.name.trim(),
      description: typeof raw.description === 'string' && raw.description.trim()
        ? raw.description.trim()
        : catalog?.shortDescription ?? `Legacy metric declaration for ${raw.name.trim()}.`,
      kind: normalizedScoring ? 'model_judge' : (raw.kind ?? catalog?.kind ?? 'custom'),
      valueType: raw.valueType ?? catalog?.valueType ?? 'number',
      direction: raw.direction === 'minimize' ? 'minimize' : (catalog?.defaultDirection ?? 'maximize'),
      primary: Boolean(raw.primary),
      unit: raw.unit ?? catalog?.unit,
      scoring: normalizedScoring,
    }]
  })
}

export function makeCatalogMetric(entry: MetricCatalogEntry, isPrimary: boolean): DesignMetric {
  return {
    id: newMetricId(),
    catalogKey: entry.key,
    name: entry.name,
    description: entry.shortDescription,
    kind: entry.kind,
    valueType: entry.valueType,
    direction: entry.defaultDirection,
    primary: isPrimary,
    unit: entry.unit,
  }
}

export function makeCustomMetric(input: { name: string; description: string; direction: MetricDirection; valueType?: MetricValueType; unit?: string; scoring?: MetricScoringConfig }, isPrimary: boolean): DesignMetric {
  return {
    id: newMetricId(),
    name: input.name.trim(),
    description: input.description.trim(),
    kind: input.scoring ? 'model_judge' : 'custom',
    valueType: input.valueType ?? 'number',
    direction: input.direction,
    primary: isPrimary,
    unit: input.unit?.trim() || undefined,
    scoring: input.scoring,
  }
}

// Metric IDs have the same browser requirement as canvas IDs: they must work
// in plain-HTTP development deployments as well as HTTPS, where
// crypto.randomUUID() is unavailable.
function newMetricId(): string {
  return newNodeId().replace(/^node-/, 'metric-')
}
